#+title: DUNE TDR repository structure

Here is a tour of the general layout of files and directories in
the repo or in your working directory. More detail is given in Chapter 6 of the guidance document.

- [[./dune.cls]] holds most of the setup for large DUNE documents.  It's
  not much more than using a bunch of LaTeX packages.

- [[./common/]] Directory that holds the files preamble, init, and final that include LaTeX bits required by all the volumes. Please don't touch these aforementioned files. Other files in "common" that you should reference and may even add to are:
  - defs.tex :: macros that should be used instead of "hard coding" something.
  - units.tex :: proper way to "spell" numbers with or without units.
  - citedb.bib :: (or similar name ~.bib~) the BibTeX bibliography database
  - glossary.tex :: a glossary database 
  
Guidelines for editing these files are in the guidance document. Please follow best practices! Many people will need to update these files, so always pull down the latest version before you start, then push your changes soon after you finish.

- ~figures/~ or ~graphics/~ holds graphics files (PDF, JPEG, PNG)

- ~util/~ holds tools that can be used to build a volume

- ~generated/~ in the case that files are generated and committed,
  they go here.  Never hand-edit these files as changes will be lost
  next time they are regenerated.  Instead modify whatever generates
  them.

- ~shared/~ some documents have LaTeX content which must be identical across
  volumes or other units.  That goes here.

- ~vol*/~ per-volume directory, each with an accompanying (top-level)
  ~vol*.tex~ file.  ~vol*.tex~ is the file that you build.

- ~build/~ produced by Waf.  Do *not* commit this, and be sure to add it to
  the [[./gitignore]] file.

- ~install/~ possibly created by ~waf --prefix=install~.  Do *not*
  commit this, and be sure to add it to the [[./gitignore]] file.

- ~latexmk*/~ if you use ~latexmk~ to build the document, this directory will be created to hold the output. 

Not all these exist in all document repos or working areas.




