#+TITLE: Guidance For Documents


This repository holds the source for a document to provide guidance on writing

- [[https://github.com/DUNE/lbne-fd-closeout][The DUNE Far Detector Closeout]]
- [[https://github.com/DUNE/lbn-cdr][The DUNE CDR]]

These and other documents, including the
[[https://github.com/DUNE/cern-prototype-proposal][Proposal for a Full-Scale, Single-Phase Prototype at CERN]] are organized through the
[[https://web.fnal.gov/project/LBNF/ReviewsAndAssessments/CD-1Preparation/SitePages/CD-1%20Preparation%20Home.aspx][CD-1 Preparation Page]].

This guidance is in the form of a LaTeX document which tries to follow its own guidance and thus can be used as an extended example.  Built PDFs of the guidance document are available from the [[https://github.com/DUNE/document-guidance/releases][GitHub releases area for this repository]].

* Getting started

This section describes how to check out the source to this document-guidance document,
edit and build it and to push commits back.  Substitute the actual document repository name for =document-guidance= in the following examples:

** Initial clone

If you've just gone through the "Install on Mac" procedure, skip this step.
To start with you must "clone" each remote repository that you need from GitHub.  Each GitHub repository web site provides a URL on the right-hand sidebar.  The HTTPS URL can be used for anonymous clone and then later can be pushed to (see below) by supplying your GItHub password.  The SSH URL requires uploading a public key to GitHub but then no password need be given.  Pick the URL you like and then cloning is simple:

#+BEGIN_EXAMPLE
  $ cd /my/work/area
  $ git clone <URL>
#+END_EXAMPLE

For example, to clone this repository using the HTTPS URL one would do:

#+BEGIN_EXAMPLE
  $ cd /my/work/area
  $ git clone https://github.com/DUNE/document-guidance.git
  $ cd document-guidance
#+END_EXAMPLE

** Building the documents

To build the documents you need `pdflatex` and `bibtex`.  In each repository there will be one or more main LaTeX file with a correspondingly named sub-directory holding the bulk of the =.tex= files.  

#+BEGIN_EXAMPLE
  $ pdflatex guidance
  $ bibtex guidance
  $ pdflatex guidance
  $ pdflatex guidance
#+END_EXAMPLE

Unless references change, it is usually sufficient for subsequent
builds to run only:

#+BEGIN_EXAMPLE
  $ pdflatex guidance
#+END_EXAMPLE

You may need to run this command twice to get the paging and numbering
correct.

The documents use the [[./cdr.cls][cdr.cls]] class are by default built with editing
markup.  The technical editors are responsible for producing a clean
and properly built version of any document for internal and final
release but anyone may attempt to produce a "final" version themselves.
To do that, replace each =pdflatex guidance= command
with this one like:

#+BEGIN_EXAMPLE
   $ pdflatex "\def\isfinal{1} \input{guidance}"
#+END_EXAMPLE

* Autobuilder

A PDF of the documented is generated through the services of [[https://www.sharelatex.com][ShareLaTeX]]

  https://www.sharelatex.com/github/repos/DUNE/document-guidance

An alternative auto-built PDF is available [[https://dune.bnl.gov/tmp/][here]].

* Repository

It is strongly recommended that any changes made to a document be
committed to your local git clone and then pushed back to GitHub.  To
get "push" access to this repository send your GitHub user name to
Brett (see contacts below) and indicate to which repository you need
access.  (If you instead prefer to fork and issue pull requests that
can likely be accommodated.  Check with the document technical
editors.)

** General git procedure:

If you installed the GitHub for Mac (instructions above), you can use the GUI provided to
pull, commit and push, if you prefer.

#+BEGIN_EXAMPLE
  $ cd lbn-cdr
  # Before you start, it's wise to pull down the latest commits from others
  $ git pull
  # Edit your files, save your changes, and test that the document compiles.
  # If any of your files are new, add it/them before committing, e.g.,:
  $ git add volume-x/the-new-file.tex
  $ git add volume-x/figures/the-new-picture.pdf
  ...
  $ git commit -a -m "Some commit message"
  $ git push
#+END_EXAMPLE

If any commits have been pushed by others since the last time you did a =git pull= (or since your initial =git clone=) then git will not allow you to =push= until you have done a fresh =git pull=.  

If =git pull= doesn't work due to a conflict, "stash" your changes, pull in the latest commits (it should work after git stash), then "unstash" or "pop" your changes back in and resolve conflicts.

#+BEGIN_EXAMPLE
  $ git stash
  $ git pull
  $ git stash pop
  # Resolve the conflicts in the affected file(s)
  # Make sure the entire document compiles
  $ git commit -a -m "Some commit message"
  $ git push
#+END_EXAMPLE

** Git-phobic

Git works on all major computing platforms and many minor ones and is
successfully used by all manner of people, even Physicists.  If for
some reason you are incapable to use Git you will be accommodated at
the cost of additional burden placed on the technical editors.  To
submit contributions outside of Git, follow this procedure:

- Start editing from the most recent tagged release:
  -  [[https://github.com/DUNE/lbn-cdr/releases][lbn-cdr]]
  -  [[https://github.com/DUNE/lbne-fd-closeout/releases][lbne-fd-closeout]]
  -  [[https://github.com/DUNE/document-guidance/releases][document-guidance]]

- Unpack the release archive (.zip or .tar.gz) on your computer.
- Make your edits inside the directory/folder that is created.
- When you have finished, remove any generated files (eg, =*.pdf=).
- Repack the directory (as `.zip` or `.tar.gz`).
- Upload this archive to the [[https://web.fnal.gov/project/LBNF/ReviewsAndAssessments/CD-1Preparation/Shared%20Documents/Forms/AllItems.aspx][Contributions Library]]. ([[https://fermi.service-now.com/kb_view.do?sysparm_article=KB0010542][FNAL Services account]] required)

If you are unable to edit in LaTeX, please talk to Anne (see contacts below).

* Contacts

- Anne Heavey <aheavey@fnal.gov> 630-840-8039 (technical editor, content)

- Brett Viren <bv@bnl.gov> (technical editor, LaTeX machinery and repository)
