#+TITLE: Guidance for contributing to DUNE documents

* This repository

This *repository* holds the source for a document that provides guidance on writing and editing design reports in LaTeX according to the standards that we've set up for DUNE and LBNF. It is designed to follow its own guidance and thus can be used as an extended example and as a reference. Previous versions of the guidance document have been used for:
- [[https://github.com/DUNE/Technical-Proposal][The DUNE IDR]] (which was initially called the Technical Proposal), 
- [[https://github.com/DUNE/protodune-tdr][The ProtoDUNE-SP TDR]], 
- [[https://github.com/DUNE/lbn-cdr][The DUNE CDR]], 
- [[https://github.com/DUNE/lbne-fd-closeout][The DUNE Far Detector Closeout]], and
- [[https://github.com/DUNE/dune-tdr][The DUNE TDR]]

Please look at the LaTeX files under the "guidance" directory to see how to make headings, labels, tables, figures, etc., according to standards we've set. Compare it to the built [[https://dune.bnl.gov/docs/guidance.pdf][PDF of the document]].

See [[https://wiki.dunescience.org/wiki/Technical_Design_Report][the wiki pages for the TDR]] for information on coordination and management for the DUNE TDR. 

* Need Help?

- [[./git.org][Help on using ~git~ and GitHub]]
- [[./tools.org][Help on building the documents]]
- [[./latex.org][Help on DUNE LaTeX]]

For more help:

- Anne Heavey <aheavey@fnal.gov> 630-840-8039 (technical editor, structure, style)

- Brett Viren <bv@bnl.gov> (LaTeX machinery and repository)

- David DeMuth <david.demuth@vcsu.edu> (LaTeX, images, general)
